Resources:
  CelestialBodiesTable:
    Type: AWS::DynamodB::Table
    Properties:
      TableName: "CelestialBodies"
      AttributeDefinitions:
        - AttributeName: "celestialBodyId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "celestialBodyId"
          AttributeType: "S"
      BillingMode: "PAY_PER_REQUEST"