Resources:
  SolarSystemsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: SolarSystems
      AttributeDefinitions:
        - AttributeName: "solarSystemId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "solarSystemId"
          KeyType: "HASH"
      BillingMode: "PAY_PER_REQUEST"

